# Generated by Django 3.0 on 2022-09-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220912_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
